Revert "Update batik library in mpsutil.plantuml"
This reverts commit fa1737f2e839847ce5aa4487834e4b2480b435dd.

It fails with MPS 2018.2 RC1:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.intellij.util.SVGLoader$MySVGDOMImplementation
    at com.intellij.util.SVGLoader$MySAXSVGDocumentFactory.<init>(SVGLoader.java:268)
    at com.intellij.util.SVGLoader.<init>(SVGLoader.java:227)
    at com.intellij.util.SVGLoader.load(SVGLoader.java:192)